In [4]:
from sklearn import preprocessing
import numpy as np
X=np.array([[1.,-1.,2.],
           [2.,0.,0.],
           [0.,1.,-1.]])


In [5]:
X

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [6]:
X_scaled=preprocessing.scale(X)#not to be used the function below should be used

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [10]:
scaler=preprocessing.StandardScaler()
scaler.fit(X)
scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])