In [9]:
from sklearn import datasets,model_selection
from sklearn.naive_bayes import GaussianNB
import pandas as pd
import numpy as np
boston=datasets.load_iris()
x=boston.data
y=boston.target
X_train,X_test,Y_train,Y_test=model_selection.train_test_split(x,y,test_size=0.25,random_state=1)


In [10]:
clf=GaussianNB()
clf.fit(X_train,Y_train)


GaussianNB(priors=None)

In [11]:
Y_pred=clf.predict(X_test)


In [12]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(Y_test,Y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        13
          1       1.00      0.94      0.97        16
          2       0.90      1.00      0.95         9

avg / total       0.98      0.97      0.97        38



In [13]:
print(confusion_matrix(Y_test,Y_pred))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
